### ISSUE TITLE
Database connectivity issue

### ISSUE THREAD

**Issue by HRDevelops** [cadofoh/simple_events_booking_website#1]
![Aston Events and 3 more pages - Work - Microsoft​ Edge 1_17_2023 9_58_00 AM](https://user-images.githubusercontent.com/89375202/212813617-80e5de4c-6746-45c8-89f3-71307f663c88.png)
Kindly attach the database queries file with it.

**Comment by cadofoh** [comment]
[db.zip](https://github.com/cadofoh/simple_events_booking_website/files/10437606/db.zip)
